<?php




//addition of previously exported custom fields
if( function_exists('acf_add_local_field_group') ):

//slideshow group
acf_add_local_field_group(array(
	'key' => 'group_57854f05fdsdfd566e',
	'title' => 'Home Page Slideshow',
	'fields' => array(
		array(
			'key' => '5jngdskjn_559gfshfdgsc0frew52e54f21',
			'label' => 'Slide Text',
			'name' => 'static-slideshow-text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'toolbar' => 'full',
			'media_upload' => 1,
			'tabs' => 'all',
		),
		array(
			'key' => 'slideshoretwgfshfdgsw-cta',
			'label' => 'Slide CTA',
			'name' => 'static-slideshow-cta',
			'type' => 'text',
			'instructions' => '*optional*',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50%',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
			),
			'taxonomy' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
		),
		array(
			'key' => 'slideshotgfshfdgsreww-cta-link',
			'label' => 'Link for CTA',
			'name' => 'static-slideshow-cta-link',
			'type' => 'text',
			'instructions' => '*optional* Copy and paste a link, don\'t forget http://',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50%',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
			),
			'taxonomy' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
		),
		array(
			'key' => '5jn85fgsdfgsdf7f6cfdsfd7feea',
			'label' => 'Swoosh Image',
			'name' => 'swoosh-image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'hidden',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => '5jngdskjn_57857ffsfd577fee8',
			'label' => 'Slides',
			'name' => 'repeatable-home-slides',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '5jngdskjn_57857f6cfdsfd7feea',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add New Slide',
			'sub_fields' => array(
				array(
					'key' => '5jngdskjn_57857f6cfdsfd7feea',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => 'Upload image - exact size required 1500px x 550px @ 72dpi',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => '5jngdskjn_559c0frew52e54f21',
					'label' => 'Slide Text',
					'name' => 'slideshow-text',
					'type' => 'wysiwyg',
					'instructions' => 'Per-slide text. Note: does not display for every theme',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 1,
					'tabs' => 'all',
				),
				array(
					'key' => 'slideshoretww-cta',
					'label' => 'Slide CTA',
					'name' => 'slideshow-cta',
					'type' => 'text',
					'instructions' => 'Enter text for a CTA that sits below slideshow text ex:\'Learn More\', \'Shop Now!\'',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50%',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
					),
					'taxonomy' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'slideshotreww-cta-link',
					'label' => 'Link for CTA',
					'name' => 'slideshow-cta-link',
					'type' => 'text',
					'instructions' => 'Copy and paste a link, don\'t forget http://',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50%',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
					),
					'taxonomy' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'page-home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

//home columns
// acf_add_local_field_group(array(
// 	'key' => 'group_5a0ca2rref094b60',
// 	'title' => 'Home Columns',
// 	'fields' => array(
// 		array(
// 			'key' => '5jngdskjn_5a0ca34f88634',
// 			'label' => 'Home Columns',
// 			'name' => 'home_columns',
// 			'type' => 'repeater',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => '5jngdskjn_5a0ca36e88635',
// 			'min' => 0,
// 			'max' => 0,
// 			'layout' => 'block',
// 			'button_label' => '',
// 			'sub_fields' => array(
// 				array(
// 					'key' => '5jngdskjn_5a0ca36e88635',
// 					'label' => 'Home Columns Row of 3',
// 					'name' => '',
// 					'type' => 'message',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'message' => '',
// 					'new_lines' => 'wpautop',
// 					'esc_html' => 0,
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca38788636',
// 					'label' => 'Left Column Title',
// 					'name' => 'left_column_title',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '33',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca3d588637',
// 					'label' => 'Middle Column Title',
// 					'name' => 'middle_column_title',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '33',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca3e588638',
// 					'label' => 'Right Column Title',
// 					'name' => 'right_column_title',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '34',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca73faf819',
// 					'label' => 'Title Below Image?',
// 					'name' => 'title_below_image_left',
// 					'type' => 'true_false',
// 					'instructions' => 'If left checked, title will appear below image. Otherwise it will appear above the image.',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '33',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'message' => '',
// 					'default_value' => 0,
// 					'ui' => 0,
// 					'ui_on_text' => '',
// 					'ui_off_text' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca7a0af81a',
// 					'label' => 'Title Below Image?',
// 					'name' => 'title_below_image_middle',
// 					'type' => 'true_false',
// 					'instructions' => 'If left checked, title will appear below image. Otherwise it will appear above the image.',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '33',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'message' => '',
// 					'default_value' => 0,
// 					'ui' => 0,
// 					'ui_on_text' => '',
// 					'ui_off_text' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca7a7af81b',
// 					'label' => 'Title Below Image?',
// 					'name' => 'title_below_image_right',
// 					'type' => 'true_false',
// 					'instructions' => 'If left checked, title will appear below image. Otherwise it will appear above the image.',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '34',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'message' => '',
// 					'default_value' => 0,
// 					'ui' => 0,
// 					'ui_on_text' => '',
// 					'ui_off_text' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca40188639',
// 					'label' => 'Left Column Image',
// 					'name' => 'left_column_image',
// 					'type' => 'image',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '33',
// 						'class' => 'clear-left',
// 						'id' => '',
// 					),
// 					'return_format' => 'array',
// 					'preview_size' => 'thumbnail',
// 					'library' => 'all',
// 					'min_width' => '',
// 					'min_height' => '',
// 					'min_size' => '',
// 					'max_width' => '',
// 					'max_height' => '',
// 					'max_size' => '',
// 					'mime_types' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca4148863a',
// 					'label' => 'Middle Column Image',
// 					'name' => 'middle_column_image',
// 					'type' => 'image',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '33',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'return_format' => 'array',
// 					'preview_size' => 'thumbnail',
// 					'library' => 'all',
// 					'min_width' => '',
// 					'min_height' => '',
// 					'min_size' => '',
// 					'max_width' => '',
// 					'max_height' => '',
// 					'max_size' => '',
// 					'mime_types' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca42a8863c',
// 					'label' => 'Right Column Image',
// 					'name' => 'right_column_image',
// 					'type' => 'image',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '34',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'return_format' => 'array',
// 					'preview_size' => 'thumbnail',
// 					'library' => 'all',
// 					'min_width' => '',
// 					'min_height' => '',
// 					'min_size' => '',
// 					'max_width' => '',
// 					'max_height' => '',
// 					'max_size' => '',
// 					'mime_types' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca4408863d',
// 					'label' => 'Left Column Description',
// 					'name' => 'left_column_description',
// 					'type' => 'wysiwyg',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '33',
// 						'class' => 'clear-left',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'tabs' => 'all',
// 					'toolbar' => 'full',
// 					'media_upload' => 1,
// 					'delay' => 0,
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca4688863e',
// 					'label' => 'Middle Column Description',
// 					'name' => 'middle_column_description',
// 					'type' => 'wysiwyg',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '33',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'tabs' => 'all',
// 					'toolbar' => 'full',
// 					'media_upload' => 1,
// 					'delay' => 0,
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca4888863f',
// 					'label' => 'Right Column Description',
// 					'name' => 'right_column_description',
// 					'type' => 'wysiwyg',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '34',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'tabs' => 'all',
// 					'toolbar' => 'full',
// 					'media_upload' => 1,
// 					'delay' => 0,
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca49b88640',
// 					'label' => 'Left Column CTA',
// 					'name' => 'left_column_cta',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '17',
// 						'class' => 'clear-left',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca4c688641',
// 					'label' => 'Left Column Link',
// 					'name' => 'left_column_link',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '16',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca4db88642',
// 					'label' => 'Middle Column CTA',
// 					'name' => 'middle_column_cta',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '17',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca50488644',
// 					'label' => 'Middle Column Link',
// 					'name' => 'middle_column_link',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '16',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca4f088643',
// 					'label' => 'Right Column CTA',
// 					'name' => 'right_column_cta',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '17',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => '5jngdskjn_5a0ca53d88646',
// 					'label' => 'Right Column Link',
// 					'name' => 'right_column_link',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '17',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 			),
// 		),
// 	),
// 	'location' => array(
// 		array(
// 			array(
// 				'param' => 'page_template',
// 				'operator' => '==',
// 				'value' => 'page-home.php',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));


//additional home page content
acf_add_local_field_group(array(
	'key' => 'group_5sdaa0b1ff3ecbce',
	'title' => 'Additional Home Page Content',
	'fields' => array(
		array(
			'key' => '5jngdskjn_5a0b201cab7f5',
			'label' => 'Include additional homepage content?',
			'name' => 'include_additional_homepage_content',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => '5jngdskjn_5a0b20ceab7f6',
			'label' => 'Section Title',
			'name' => 'section_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => '5jngdskjn_5a0b201cab7f5',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => '5jngdskjn_5a0b42ebfbf31',
			'label' => 'Shortcodes',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => '5jngdskjn_5a0b201cab7f5',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Paste these shortcodes to include info from the <a href=\'admin.php?page=contact-info\' target=\'_blank\'>"Contact Information"</a> section:
<strong>[gon-address] [gon-phone] [gon-office-photo] [gon-google-iframe]. </strong>
Use location="handle" to get contact information from a secondary location ( example <strong>[gon-office-photo location="baton-rouge"]</strong> )',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => '5jngdskjn_5a0c931ec2ca6',
			'label' => 'Content Columns',
			'name' => 'content_columns',
			'type' => 'repeater',
			'instructions' => 'Max 3 columns. Content will display in equal width columns depending on how many content sections you create. (ex: if you only create one column, content will display full width. If you create 2 columns, content will display in two columns, each with a width of 50%)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => '5jngdskjn_5a0b201cab7f5',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '5jngdskjn_5a0c944933069',
			'min' => 0,
			'max' => 3,
			'layout' => 'block',
			'button_label' => 'Add Column',
			'sub_fields' => array(
				array(
					'key' => '5jngdskjn_5a0c944933069',
					'label' => 'Content Column',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'key' => '5jngdskjn_5a0c93c7c2ca7',
					'label' => 'Content',
					'name' => 'content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'page-home.php',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
